# **101 Numpy Exercises for Data Analysis (Python)**

The goal of the numpy exercises is to serve as a reference as well as to get you to apply numpy beyond the basics. The questions are of 4 levels of difficulties with L1 being the easiest to L4 being the hardest.

**1. Import numpy as np and see the version**  
Difficulty Level: L1

Q. Import numpy as `np` and print the version number.

In [1]:
import numpy as np
print(np.__version__)

1.21.0


**2 How to create a 1D array?**

Difficulty Level: L1

Q. Create a 1D array of numbers from 0 to 9

Desired output:

#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**3. How to create a boolean array?**

Difficulty Level: L1

Q. Create a 3×3 numpy array of all True’s

In [14]:
np.full((3,3), True, dtype = 'bool')

# or
# np.ones((3,3), dtype = 'bool') 


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

**4. How to extract items that satisfy a given condition from 1D array?** 

Difficulty Level: L1

Q. Extract all odd numbers from arr

Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired output:

#> array([1, 3, 5, 7, 9])

In [15]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [17]:
arr[arr%2==1]

array([1, 3, 5, 7, 9])

**5. How to replace items that satisfy a condition with another value in numpy array?**

Difficulty Level: L1

Q. Replace all odd numbers in arr with -1

Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired Output:

#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [21]:
arr[arr%2==1]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

**6. How to replace items that satisfy a condition without affecting the original array?**

Difficulty Level: L2

Q. Replace all odd numbers in arr with -1 without changing arr

Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired Output:

out
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

arr
#>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_copy = arr.copy()
arr_copy[arr_copy%2==1] = -1
print(arr_copy)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [41]:
print(np.where(arr%2==0, arr, -1))
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


**_Lessons_**

In this code, I learnt about np.where which takes a condition in this case arr%2==0
the second arguement is arr, which is the array where the condition is checked,
the third element, in this case -1, is the value that is returned when the condition fails on the first array

NOTE, the two arrays are broadcasted to match.

an alternative to the code written below is:  
`print(np.where(arr%2==1, -1, arr))`

**7. How to reshape an array?**

Difficulty Level: L1

Q. Convert a 1D array to a 2D array with 2 rows

Input:

np.arange(10)

#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired Output:

#> array([[0, 1, 2, 3, 4],  
#>          [5, 6, 7, 8, 9]])

In [44]:
arr = np.arange(10)
print(arr)
print(arr.reshape(2,-1))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


**8. How to stack two arrays vertically?**

Difficulty Level: L2

Q. Stack arrays a and b vertically

Input

a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

Desired Output:

#> array([[0, 1, 2, 3, 4],

#>        [5, 6, 7, 8, 9],

#>        [1, 1, 1, 1, 1],

#>        [1, 1, 1, 1, 1]]

In [49]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

**_Lessons_**  
1). Learnt about `np.repeat`

2). `np.vstack` takes a tuple as its arguements and not just a bare list of arguements

*other solutions:*

In [ ]:
# solution 2
