In [3]:
import numpy as np

In [4]:
np.random.seed(0)

In [5]:
!pwd

/content


In [6]:
x1 = np.random.randint(10,size=6) # One-dimensional array
x2 = np.random.randint(10,size=(3,4)) #Two-dimensional array
x3 = np.random.randint(10,size=(3,4,5)) #Three-dimensional array

In [7]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [8]:
print("dtype:", x3.dtype)

dtype: int64


In [9]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In [10]:
x1

array([5, 0, 3, 3, 7, 9])

In [11]:
x1[0]

5

In [12]:
x1[4]

7

In [13]:
x1[-2]

7

In [14]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [15]:
# in a two-dimensional array, teh values can be accessed
# using comma separated tuple of indices
# the first one refers to the first dimension(the outermost), 
# i.e the row in the case of a two dimensional array
x2[0,0]

3

In [16]:
x2[2,3]

7

In [17]:
x2[-3,-1]

4

In [18]:
# values can also be changed through indexing
x2[0,0]=10
x2

array([[10,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

## One-Dimensional Subarrays

In [19]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
x[:5] # first five elements

array([0, 1, 2, 3, 4])

In [21]:
x[5:] # elements after index 5

array([5, 6, 7, 8, 9])

In [22]:
x[::2] #every 2nd element beginning with the first

array([0, 2, 4, 6, 8])

 ## Multi-Dimensional subarrays

In [23]:
x2

array([[10,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [24]:
x2[:2,:3]

array([[10,  5,  2],
       [ 7,  6,  8]])

In [25]:
x2[:3,::2]

array([[10,  2],
       [ 7,  8],
       [ 1,  7]])

In [26]:
x2[::-1,::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 10]])

In [27]:
x2[:,0]

array([10,  7,  1])

In [28]:
x2[0]

array([10,  5,  2,  4])

In [29]:
x2[0,:]

array([10,  5,  2,  4])

### Copies of arrays
One major difference between Numpy array slicing and python list slicing is the fact that, Numpy array slicing does not produce a copy of the slice but rather a _view_ of the slice from the original while python slices produce a copy. Observe:

In [30]:
print(x2)

[[10  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Let us extract a 2x2 subarray:

In [31]:
x2_sub = x2[:2,:2]
print(x2_sub)

[[10  5]
 [ 7  6]]


Let us then modify the subarray, and you will see that the original is also changed

In [32]:
x2_sub[0,0]=99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [33]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


You realize that the original content is changed when we change the subarray. Therefore, to copy a subarray, we need to use the copy() method

In [34]:
x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [35]:
x2_sub_copy[0,0]= 20
print(x2_sub_copy)

[[20  5]
 [ 7  6]]


In [36]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## Reshaping Arrays
Arrays can be reshaped using *reshape* method or use of _newaxis_ keyword with a slice operator

In [37]:
x = np.array([1,2,3,4])
x.reshape((1,4))

array([[1, 2, 3, 4]])

In [38]:
x[np.newaxis,:]

array([[1, 2, 3, 4]])

In [39]:
x[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4]])

# Concatenation and Splitting

In [40]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [41]:
z = np.array([9,4,1])
print(np.concatenate([x,y,z]))

[1 2 3 3 2 1 9 4 1]


In [42]:
grid = np.array([[1,2,3],
                [4,5,6]])

In [43]:
# concatenate along teh first axes
np.concatenate([grid,grid*10])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

In [44]:
np.concatenate([grid,grid*10], axis=1)

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60]])

In [45]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],
                [6,5,4]])
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [46]:
y = np.array([[2],
              [2]])
np.hstack([grid,y])

array([[9, 8, 7, 2],
       [6, 5, 4, 2]])

In [47]:
np.dstack([x,x])

array([[[1, 1],
        [2, 2],
        [3, 3]]])

In [48]:
np.vstack([x,x])

array([[1, 2, 3],
       [1, 2, 3]])

In [49]:
np.hstack([x,x])

array([1, 2, 3, 1, 2, 3])

## Splitting Arrays

In [50]:
x = np.array([1,2,3,1,4,9,1,8,27])
x1,x2,x3=np.split(x,[3,6])
print(x1,x2,x3)

[1 2 3] [1 4 9] [ 1  8 27]


In [51]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [54]:
upper, lower = np.vsplit(grid,[2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [56]:
left,right = np.hsplit(grid,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
