In [2]:
import numpy as np
np.random.seed(0)

this function calculates the reciprical of values inside a numpy array one by one and then outputs the values.

In [5]:
def reciprical(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i]=1.0/values[i]
    return output

values = np.random.randint(1,10,size=5)
reciprical(values)

array([0.14285714, 0.11111111, 0.11111111, 0.5       , 0.14285714])

the operation seems to run in **normal** time. But this is not the case for very *big arrays*, observe:

In [6]:
big_array = np.random.randint(1,100, size = 1000000)
%timeit reciprical(big_array)

1 loop, best of 5: 2.24 s per loop


Python is slow in this operatin because of it dynamic typing. The execution itself is  not so expensive as the cost of type-checking done by the interpreter in the background. Thus, with a compiled languare like C or Java, the code runs much faster because it is statically typed

###Intro to UFuncs
This is where Numpy UFuncs come into play. Numpy provides a feature that allows us to perform the operations for the statically typed numpy arrays. This is known as *Vectorization*. This is where you simply apply an operation to the array rather to than to each individual element in the array using a loop as we saw earlier. The vectorization approacehs pushes the executio of the loop to compile time which save a lot of time.

In [10]:
# using a for loop
print("Function:     ",reciprical(values))
# using vectorization
print("Vectorization:",1.0/values)

Function:      [0.14285714 0.11111111 0.11111111 0.5        0.14285714]
Vectorization: [0.14285714 0.11111111 0.11111111 0.5        0.14285714]


In [11]:
%timeit(1.0/big_array)

1000 loops, best of 5: 1.59 ms per loop


Even more, UFuncs can be used between an array and an array, observe:

In [12]:
np.arange(5)/np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

Ufuncs can also operate on multi-dimensional arrays

In [14]:
x=np.arange(9).reshape((3,3))
print(x)
2**x

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])